AWSTemplateFormatVersion: '2010-09-09'
Description: 'Project resources for CloudFront and S3'

Parameters:
  Environment:
    Description: 'Allowed environment names are: dev, qa, stg, prod'
    AllowedValues: [dev, qa, stg, prod]
    Type: String
  
  Proj:
    Description: 'Project name in lowercase'
    Type: String
  
  DomainName:
    Description: 'Domain name for the CloudFront distribution'
    Type: String

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']

Resources:
  ####################
  ######## S3 ########
  ####################
  ProjectBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub '${Proj}-${Environment}-${AWS::Region}-frontend-${AWS::AccountId}'

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProjectBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${ProjectBucket}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  ####################
  ######## WAF #######
  ####################
  ProductionWebACL:
    Type: AWS::WAFv2::WebACL
    Condition: IsProd
    Properties:
      Name: !Sub '${Proj}-${Environment}-webacl'
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSetMetric

  ####################
  #### CLOUDFRONT ####
  ####################
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${Proj}-${Environment}-OAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt ProjectBucket.RegionalDomainName
            Id: S3Origin
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            S3OriginConfig: {}
        Aliases: !If 
          - IsProd
          - [!Ref DomainName]
          - [!Sub '${Environment}.${DomainName}']
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        Comment: !Sub 'CloudFront Distribution for ${Proj}-${Environment}'
        WebACLId: !If [IsProd, !GetAtt ProductionWebACL.Arn, !Ref 'AWS::NoValue']
        PriceClass: PriceClass_All
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:009160044639:certificate/28adc530-04a9-405c-af96-996043c671ac
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: /index.html
            ResponseCode: 200
          - ErrorCode: 404
            ResponsePagePath: /index.html
            ResponseCode: 200

Outputs:
  CloudFrontDistributionDomainName:
    Description: 'Domain name of the CloudFront distribution'
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomain'
  
  CloudFrontDistributionId:
    Description: 'ID of the CloudFront distribution'
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontId'