name: Deploy Frontend Infrastructure
on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - dev
    # paths:
    #   - 'templates/**'

jobs:
  validate:
    name: Validate Templates
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  deploy:
    name: Deploy Infrastructure
    needs: validate
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }} 
          audience: sts.amazonaws.com

      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: frontend-infra-${{ github.ref_name }}
          template: templates/main.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: |
            Environment=${{ github.ref_name }},
            Project=solutions-poc-frontend,
            DomainName=${{ vars.DOMAIN_NAME }},
            ActiveEnvironment=${{ vars.ACTIVE_COLOR || 'blue' }} 